import pyautogui as ag
import keyboard
from time import sleep as zz
import pyperclip



# INSTRUÇÕES:
# • Abra o chrome, maximize a janela e feche


def enviarEmail(email):
    ag.hotkey('ctrl', 't')
    zz(2)
    ag.write('https://accounts.zoho.com/signin?servicename=VirtualOffice&signupurl=https://www.zoho.com/workplace/pricing.html')
    ag.press('enter')
    zz(20)
    keyboard.write('leonardo@boxcontabil.com.br')
    zz(1)
    keyboard.write('***')
    zz(10)
    p4 = ag.locateOnScreen('C:\\Users\\Leonardo\\Documents\\MeusProjetos\\Python\\Emissao_NFSe_Ana_e_Inaia\\img\\p4.PNG')
    while True:
         if p4 == ag.locateOnScreen('C:\\Users\\Leonardo\\Documents\\MeusProjetos\\Python\\Emissao_NFSe_Ana_e_Inaia\\img\\p4.PNG'):
              ag.press('pagedown')
              zz(1)
              ag.click(x=1184,y=644)
              zz(5)
              break
         else:
              print('[ERRO] IMAGEM NÃO ENCONTRADA')
    ctrlF(1,'novo e-mail')
    zz(5)
    ag.write(email)
    ag.press(['tab', 'tab'])
    zz(2)
    ag.write(f'NFSe - Dra. ANA LUIZA MARTINELI VOLPI ZANCHINI BARRELLA')
    ag.press('tab')
    zz(2)
    kb.write(f'Olá, tudo bem? \nSegue nota fiscal.')
    zz(1)
    ag.click(x=260,y=351)
    zz(5)
    ag.click(x=648, y=408)
    zz(5)
    ag.click('C:\\Users\\Leonardo\\Documents\\MeusProjetos\\Python\\Emissao_NFSe_Ana_e_Inaia\\img\\email\\05-selecao.png')
    zzz(5)
    ag.moveTo(f'C:\\Users\\Leonardo\\Documents\\MeusProjetos\\Python\\Emissao_NFSe_Ana_e_Inaia\\img\\email\\06-hoje.png')
    ag.click(x=243,y=172) # Ponto de partida (16px por arquivo) = Vou pegar 5 arquivos
    ag.keyDown('shift')
    ag.click(x=243,y=252) # Fim do mouse seleção de arquivos
    ag.keyUp('shift')
    ag.press('enter')
    zz(5)
    ag.click(f'{caminho}email\\06-anexar1.png')
    zz(25)
def enviarMensagem():
    caminho = 'C:\\Projetos_Python\\Parcelamento_de_Impostos\\img\\whatsapp\\'
    ag.hotkey('win', 'r')
    ag.write('chrome.exe')
    ag.press('enter')
    zzz(20)
    ag.write('https://web.whatsapp.com/')
    ag.press('enter')
    zzz(20)
    ag.click(f'{caminho}01-pesquisa.png')
    zzz(1)
    kb.write('#Anotações')
    zzz(1)
    ag.click(x=128,y=328)
    zzz(1)
    ag.write('Bom dia! Tudo bem?\nAcabamos de enviar as guias de parcelamento por e-mail.\n')

def baixarRelHB(login, senha):
    zz(2)
    ag.hotkey('win', 'r')
    zz(1)
    ag.write('chrome')
    zz(1)
    ag.press('enter')
    zz(1)
    ag.hotkey('ctrl', 'shift', 'n')
    zz(1)
    ag.write('https://portalprestador.hbsaude.com.br/')
    zz(1)
    ag.press('enter')
    zz(25)
    ag.click(x=676,y=313)
    ag.write(login)
    zz(1)
    ag.press('tab')
    zz(1)
    ag.write(senha)
    zz(2)
    ag.click(x=579,y=436)
    zz(2)
    ag.click(x=94,y=217)
    zz(1)
    ag.click(x=94,y=296)
    zz(1)
    ag.click(x=262,y=283)
    zz(1)
    valor = input(str('Qual é o valor da NFSe? Ex.: 3.657,50 '))
    zz(1)
    # competencia = input(str('Serviços ref à qual competência? Ex.: [Janeiro-2022] '))
    zz(1)
    ag.alert(f'Você informou o valor R${valor} e a competência {competencia}')
    zz(1)               



def salvarArquivo(nome,):
    zz(1)
    ag.click(x=1253,y=95)
    zz(1)
    p1 = ag.locateOnScreen('C:\\Users\\Leonardo\\Documents\\MeusProjetos\\Python\\Emissao_NFSe_Ana_e_Inaia\\img\\p1.PNG')
    zz(1)
    ag.doubleClick(p1)
    zz(1)
    keyboard.write('Downloads')
    zz(1)
    ag.press('enter')
    zz(2)
    ag.press('tab')
    zz(1)
    ag.press('tab')
    zz(1)
    ag.press('tab')
    zz(1)
    ag.press('tab')
    zz(1)
    ag.press('tab')
    zz(1)
    keyboard.write(f'Relatório HB {nome} {competencia}')
    zz(1)
    ag.press(['tab'] * 3)
    zz(1)
    ag.press('enter')
    zz(1)
    p2 = ag.locateOnScreen('C:\\Users\\Leonardo\\Documents\\MeusProjetos\\Python\\Emissao_NFSe_Ana_e_Inaia\\img\\p2.PNG')
    if p2 == ag.locateOnScreen('C:\\Users\\Leonardo\\Documents\\MeusProjetos\\Python\\Emissao_NFSe_Ana_e_Inaia\\img\\p2.PNG'):
        print('Já tinha arquivo igual')
        # ag.press(['tab', 'enter'])
    else:
        print('não tinha')
    zz(5)
    # ag.hotkey('ctrl', 't')
    # zz(1)
# ag.write('https://sjrp.ginfes.com.br/')
# zz(1)
# ag.press('enter')
# zz(10)
# ag.click(x=370,y=239)
# zz(5)
# ag.click(x=637,y=332)
# zz(1)
# ag.doubleClick(x=765,y=395)
# zz(1)
# keyboard.write('37355788000169')
# zz(1)
# ag.press('tab')
# zz(1)
# keyboard.write('3723620DGV75245')
# zz(1)
# ag.click(x=619,y=463)
# zz(10)
# ag.click(x=593,y=380)
# zz(5)
# ag.press(['tab'] * 5)
# zz(1)
# keyboard.write('02668512000156')
# zz(1)
# ag.press(['tab', 'enter'])
# zz(1)
# ag.press(['tab'] * 11)
# zz(1)
# keyboard.write('nfe@hbsaude.com.br')
# zz(1)
# ag.press(['tab'] * 3)
# zz(1)
# ag.press('enter')
# zz(1)
# ag.press(['tab'] * 6)
# zz(1)
# ag.press(['down', 'enter'])
# zz(3)
# ag.press(['tab'] * 11)
# zz(1)
# keyboard.write('2')
# zz(1)
# ag.press('tab')
# zz(1)
# keyboard.write(f'Serviços Médicos Prestados ref. {competencia}')
# zz(1)
# ag.press(['tab'] * 4)
# zz(1)
# keyboard.write(valor)
# zz(1)
# ag.press('tab')
# zz(1)
# ag.press('enter')
# zz(1)
# ag.press('pagedown')
# zz(1)
# ag.click(x=818,y=559)
# zz(10)
# ag.alert('CONFIRA OS DADOS E CLIQUE EM [EMITIR NFSE]')
# zz(1)
# ag.alert('APÓS CONFERIR E GERAR A NFSE, CLIQUE PARA VISUALIZAR A NFSe')
# zz(1)
# p3 = ag.locateOnScreen('C:\\Users\\Leonardo\\Documents\\MeusProjetos\\Python\\Emissao_NFSe_Ana_e_Inaia\\img\\p3.PNG')
# while True:
#      if p3 == ag.locateOnScreen('C:\\Users\\Leonardo\\Documents\\MeusProjetos\\Python\\Emissao_NFSe_Ana_e_Inaia\\img\\p3.PNG'):
#       ag.click(p3)
#       break
#      else:
#          print('[ERRO] IMAGEM P3.PNG NÃO LOCALIZADA')
#          zz(1)
# zz(1)               
# ag.click(x=1253,y=95)
# zz(1)
# p1 = ag.locateOnScreen('C:\\Users\\Leonardo\\Documents\\MeusProjetos\\Python\\Emissao_NFSe_Ana_e_Inaia\\img\\p1.PNG')
# zz(1)
# ag.doubleClick(p1)
# zz(1)
# keyboard.write('Downloads')
# zz(1)
# ag.press('enter')
# zz(2)
# ag.press('tab')
# zz(1)
# ag.press('tab')
# zz(1)
# ag.press('tab')
# zz(1)
# ag.press('tab')
# zz(1)
# ag.press('tab')
# zz(1)
# keyboard.write(f'NFSe Ana Luiza {competencia}')
# zz(1)
# ag.press(['tab'] * 3)
# zz(1)
# ag.press('enter')
# zz(1)
# p2 = ag.locateOnScreen('C:\\Users\\Leonardo\\Documents\\MeusProjetos\\Python\\Emissao_NFSe_Ana_e_Inaia\\img\\p2.PNG')
# zz(1)
# if p2 == ag.locateOnScreen('C:\\Users\\Leonardo\\Documents\\MeusProjetos\\Python\\Emissao_NFSe_Ana_e_Inaia\\img\\p2.PNG'):
#       ag.press(['tab', 'enter'])
# else:
#     print('tudo certo')
# zz(1)


zz(2)
competencia = input(str('Serviços ref à qual competência? Ex.: [Janeiro-2022] '))
# baixarRelHB('358072', '350800720')
salvarArquivo('Inaia')
ag.mouseInfo()